[docs] Add PyPI for plugin installation
Brainicism/bgutil-ytdlp-pot-provider pull request #12
Opened 2024-09-02 07:21 UTC by grqz

- Add syntax highlighting: shell
- Update docs: add plugin installation approach: PyPI

>[!NOTE]
> Merge after first PyPI release, at least after #10

2024-09-02 21:32 UTC, grqz commented
Do we actually need yt-dlp-get-pot>=0.0.2?

2024-09-04 18:08 UTC, Brainicism requested changes

2024-09-04 22:25 UTC, grqz commented on README.md
> +PyPI:
did you mean moving the github instructions after the pypi one?

2024-09-04 22:26 UTC, Brainicism commented on README.md
> +PyPI:
yes

2024-09-05 01:16 UTC, grqz commented on README.md
> +PyPI:
done in 77df1e78b5ff80deee1dd5b46e1197eacc3f174b

2024-09-05 01:17 UTC, Brainicism approved these changes

2024-09-05 01:31 UTC, grqz commented
you can merge it now if there isn't any issues

2024-09-05 02:08 UTC, merged